
set(CMAKE_EXPORT_NO_PACKAGE_REGISTRY ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS OFF)

if(NOT DEFINED ANDROID_HOME)
	set(ANDROID_HOME "$ENV{ANDROID_HOME}")
endif()

if(NOT DEFINED ANDROID_SDK)
	set(ANDROID_SDK "${ANDROID_HOME}")
endif()

if(NOT DEFINED ANDROID_NDK)
	set(ANDROID_NDK "${ANDROID_SDK}/ndk-bundle")
endif()
