FROM fedora:37

RUN yum update -y

RUN yum install -y \
    gcc \
    zlib-devel \
    openssl-devel \
    pam-devel \
    krb5-devel \
    libffi-devel \
    systemd-devel \
    libX11-devel \
    libXtst-devel \
    libXcursor-devel \
    libXrandr-devel \
    gtk2-devel \
    gtk3-devel \
    glib2-devel \
    libappindicator-devel \
    libnotify-devel \
    cups-devel \
    libusb1-devel \
    libusbx-devel \
    SDL2-devel \
    SDL2_ttf-devel
