FROM opensuse/leap:15.2

RUN zypper install -y \
    gcc \
    zlib-devel \
    libopenssl-devel \
    systemd-devel \
    xorg-x11-devel \
    libXtst-devel \
    libXcursor-devel \
    libXdamage-devel \
    libXext-devel \
    libXfixes-devel \
    libXinerama-devel \
    libxkbcommon-devel \
    libxkbfile-devel \
    libXrandr-devel \
    libXrender-devel \
    libXv-devel \
    wayland-devel \
    alsa-devel \
    libpulse-devel \
    libgsm-devel \
    libjpeg-devel \
    krb5-devel \
    pcsc-lite-devel \
    gstreamer-devel \
    gstreamer-plugins-base-devel \
    cups-devel
