FROM redhat/ubi8

RUN yum update -y

RUN yum install -y \
    gcc \
    zlib-devel \
    openssl-devel \
    pam \
    krb5-devel \
    libffi-devel \
    systemd-devel \
    libX11-devel \
    libXtst \
    libXcursor \
    libXrandr \
    gtk2 \
    gtk3 \
    glib2-devel \
    cups-libs \
    libusbx
