FROM alpine:3.17

RUN apk add --no-cache \
    gcc \
    g++ \
    openssl-dev \
    libxcursor-dev \
    libxkbfile-dev \
    libxinerama-dev \
    libxv-dev \
    libxdamage-dev \
    libxi-dev \
    libxkbcommon-dev \
    cups-dev \
    alsa-lib-dev \
    ffmpeg-dev \
    gst-plugins-base-dev \
    gsm-dev \
    libusb-dev \
    wayland-dev
