name: cbake sysroots
on: workflow_dispatch
jobs:
  build:
    name: cbake sysroot [${{matrix.distro}}-${{matrix.arch}}]
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
        distro: [ ubuntu-18.04, alpine-3.14 ]

        include:
          - os: linux
            runner: ubuntu-18.04
            
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Linux runner
        run: |
          sudo apt update
          sudo apt install ninja-build cmake xz-utils
          bash <(wget -qO - https://aka.ms/install-powershell.sh)

      - name: Build cbake sysroot
        run: |
          cd ./recipes/${{matrix.distro}}-${{matrix.arch}}
          docker buildx build . \
            -t ${{matrix.distro}}-${{matrix.arch}}-sysroot \
            --platform linux/${{matrix.arch}} \
            -o "${{matrix.distro}}-${{matrix.arch}}"
