name: cbake sysroots
on: workflow_dispatch
jobs:
  build:
    name: cbake sysroot [${{matrix.distro}}-${{matrix.arch}}]
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
        distro: 
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - debian-10
          - debian-11
          - debian-12
          - rhel8
          - rhel9
          - alpine-3.17
          - alpine-3.21

        include:
          - os: linux
            runner: ubuntu-22.04
            
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Linux runner
        run: |
          sudo apt update
          sudo apt install ninja-build cmake xz-utils
          bash <(wget -qO - https://aka.ms/install-powershell.sh)

      - name: Build cbake sysroot
        run: |
          pwsh build.ps1 sysroot -Distro ${{matrix.distro}} -Arch ${{matrix.arch}}

      - name: Upload cbake sysroot
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.distro}}-${{matrix.arch}}-sysroot
          path: packages/${{matrix.distro}}-${{matrix.arch}}-sysroot.tar.xz
